# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dentist-virtual-assistant

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .
         - name: Create env file
        run: |
          touch .env
          echo MicrosoftAppType="MultiTenant" >> .env
          echo MicrosoftAppId="bc080611-0bea-49a5-bbe9-b321c0a898d8" >> .env
          echo MicrosoftAppPassword=${{secrets.MICROSOFTAPPPASSWORD}} >> .env
          echo QnAKnowledgebaseId="641a0901-2272-4c62-9e27-6cd62a106731" >> .env
          echo QnAAuthKey=${{secrets.QNAAUTHKEY}} >> .env
          echo QnAEndpointHostName="https://dentist-assistant-qnakb.azurewebsites.net/qnamaker" >> .env
          echo LuisAppId="b52f2b84-0f43-4b68-b829-900f9e076a22" >> .env
          echo LuisAPIKey=${{secrets.LUISAPIKEY}} >> .env
          echo LuisAPIHostName="https://australiaeast.api.cognitive.microsoft.com/" >> .env
          echo SchedulerEndpoint="http://dentistscheduler-udacity.azurewebsites.net/" >> .env
          cat .env

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dentist-virtual-assistant'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C8A3F518D3D2439F833DD58600B2A8F2 }}
          package: .
